config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  namespace 'api', :path => '', :constraints => {:subdomain => "api"} do
    resources :topics 
  end

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  votes       :integer          default(0)
#  closed_at   :datetime
#

class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true

  def add_vote
    self.increment!(:votes) unless closed
  end

  private
  def closed
    self.closed_at < Time.now
  end
end

app/controllers/api/topics_controller.rb
class API::TopicsController < ApplicationController 

  def index
    @topics = Topic.all
    render json: @topics
  end

  def create
    @topic = Topic.create(topic_params)
    if @topic
      render :text => @topic.save
    end
  end


  private
  
  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @topics = Topic.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Welcome to Rubysteps
%h2 Lessons
:javascript
  $(function(){
    var get_topics = function(){
      $.ajax({
        url: "#{api_topics_path}",
        datatype: 'json',
        success: function(data){
        $.each(data, function(topic){
          $('#topics').html('<h3>'+topic.title+'</h3>');
          });
        }
      });
    };
    get_topics();
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubystepsTopics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>